"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 beer_bottleOne.glb 
Author: eder (https://sketchfab.com/eder_e)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/beer-bottle-001bb856494b44a68088d264ef5374bf
Title: Beer bottle
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function BeerBottle(props) {
  const { nodes, materials } = useGLTF("/model/beer_bottleOne.glb");
  return (
    <group {...props} dispose={null} scale={13} position={[50, -40, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.aiStandardSurface5SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.aiStandardSurface4SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.aiStandardSurface2SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.aiStandardSurface3SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/beer_bottleOne.glb");
