"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 b1.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";

gsap.registerPlugin(ScrollTrigger);

export function B1(props) {
  const { nodes, materials } = useGLTF("/model/bottleCoca.glb");

  const b1Ref = useRef(null);

  useGSAP(() => {
    // let tl = gsap.timeline({
    //   scrollTrigger: {
    //     trigger: "#landing",
    //     pin: true,
    //     start: "top top",
    //     end: "bottom top",
    //     // pinSpacer: true,
    //     pinSpacing: false,
    //     scrub: 0.9,
    //   },
    // });

    let tl2 = gsap
      .timeline({
        delay: 7,
      })
      .to(
        b1Ref.current.position,
        {
          x: 40,
          y: -24,
          z: 0,
          duration: 1.5,
        },
        "one"
      )
      .to(b1Ref.current.scale, { x: 120, y: 120, z: 120, duration: 1.5 }, "one")
      .to(
        b1Ref.current.rotation,
        {
          x: 0,
          y: 0,
          z: 0,
          duration: 1.5,
        },
        "one"
      );
  });

  return (
    <group
      ref={b1Ref}
      {...props}
      dispose={null}
      scale={340}
      position={[-200, 120, 0]}
      rotation={[Math.PI / 4, 0, 0]}
    >
      <group rotation={[-Math.PI / 2, Math.PI / 16, 0]} scale={0.047}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.Circle_Drink_0.geometry}
              material={materials.Drink}
            />
            <mesh
              geometry={nodes.Circle_DrinkLight_0.geometry}
              material={materials.DrinkLight}
            />
            <mesh
              geometry={nodes.Circle_DrinkLightYellow_0.geometry}
              material={materials.DrinkLightYellow}
            />
            <mesh
              geometry={nodes.Circle_Glass_0.geometry}
              material={materials.Glass}
            />
          </group>
          <mesh
            geometry={nodes.Circle001_Label_0.geometry}
            material={materials.Label}
            position={[0, 292.193, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[101, 101, 100]}
          />
          <mesh
            geometry={nodes.Circle002_Lid_0.geometry}
            material={materials.material}
            position={[0, 689.021, -0.828]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.Plane_Label2_0.geometry}
            material={materials.Label2}
            position={[290.431, 348.576, 198.554]}
            rotation={[3.121, 0, Math.PI]}
            scale={[155.124, 54.021, 99.98]}
          />
          <mesh
            geometry={nodes.Plane001_Logo_0.geometry}
            material={materials.Logo}
            position={[575.758, 348.576, 198.554]}
            rotation={[3.121, 0, Math.PI]}
            scale={[113.859, 54.219, 973.874]}
          />
          <mesh
            geometry={nodes.Plane002_Material002_0.geometry}
            material={materials["Material.002"]}
            position={[0, 718.748, 0]}
            rotation={[-Math.PI / 2, 0, 0.419]}
            scale={[34.694, 12.561, 82.894]}
          />
          <mesh
            geometry={nodes.Text_Text_0.geometry}
            material={materials.Text}
            position={[103.224, 616.872, 90.918]}
            rotation={[-3.13, 0, 0]}
            scale={-100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/b1.glb");
