/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 b1.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function B1(props) {
  const { nodes, materials } = useGLTF("/model/b1.glb");
  return (
    <group {...props} dispose={null} scale={83} position={[50, -37, 0]}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.161}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.aiStandardSurface5SG}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.aiStandardSurface4SG}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials.aiStandardSurface2SG}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.aiStandardSurface3SG}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/b1.glb");
